#!/bin/bash

ws=$(cat $HOME/.config/i3/config | grep "set \$workspace9" | grep -oP '"\K[^"\047]+(?=["\047])' | head -1);
i3-msg "workspace $ws; append_layout $HOME/.config/i3/layouts/chats.json"
signal-desktop &
surf web.whatsapp.com & 
sleep 0.1
surf messenger.com &
