#!/bin/bash

. $DOTS/i3/scripts/set-label

# icons from icons-in-terminal
. $HOME/.local/share/icons-in-terminal/icons_bash.sh
glyph_power=`echo -e $fa_bolt`
glyph_plug=`echo -e $oct_plug`

battery_info=$(acpi -b | grep "Battery ${BLOCK_INSTANCE}")
battery_state=$(echo "${battery_info}" | grep -wo "Full\|Charging\|Discharging")
battery_power=$(echo "${battery_info}" | grep -o '[0-9]\+%' | tr -d '%')
label="$glyph_power ${battery_power}%"
urgent_value=5
cache_full=~/.cache/i3blocks/battery_full
cache_low=~/.cache/i3blocks/battery_low
icon=$DOTS/dunst/icons/battery.png

if [[ "${battery_state}" = "Charging" || "${battery_state}" = "Full" ]]; then

	if [ -f $cache_low ]; then
		rm $cache_low
	fi

	if [[ "${battery_power}" = "100" ]]; then
		if [ ! -f $cache_full ]; then
			notify-send "Battery" "Battery is full." -i $icon
			touch $cache_full
		fi
	fi

	set-label "${label} $glyph_plug" i3.block.fgrnd
fi

if [[ "${battery_state}" = "Discharging" ]]; then

	if [ -f $cache_full ]; then
		rm $cache_full
	fi

  if [[ "${battery_power}" -lt "20" ]]; then 
		set-label "$label" i3.block.batt.5

		if [ ! -f $cache_low ]; then
			notify-send "Battery" "Battery is low." -i $icon -u CRITICAL
			touch $cache_low
		fi

	elif [[ "${battery_power}" -lt "40" ]]; then
		set-label "$label" i3.block.batt.4
	elif [[ "${battery_power}" -lt "60" ]]; then
		set-label "$label" i3.block.batt.3
	elif [[ "${battery_power}" -lt "85" ]]; then
		set-label "$label" i3.block.batt.2
	elif [[ "${battery_power}" -ge "85" ]]; then
		set-label "$label" i3.block.batt.1
	fi

  if [[ "${battery_power}" -le "${urgent_value}" ]]; then
    exit 33
  fi

fi
