#!/bin/bash

. $HOME/.config/i3/scripts/set-label

# icons from icons-in-terminal
. $HOME/.local/share/icons-in-terminal/icons_bash.sh
glyph_date=`echo -e $md_date_range`

label="$glyph_date$(date '+ %a  %Y-%m-%d')"
set-label "$label" i3.block.fgrnd

case $BLOCK_BUTTON in
  1) $HOME/.config/i3/scripts/dunst-date
esac
