#!/bin/bash

. $HOME/.config/i3/scripts/set-label

# icons from icons-in-terminal
. $HOME/.local/share/icons-in-terminal/icons_bash.sh
glyph_wifi=`echo -e $md_network_wifi`
glyph_vpn_wifi=`echo -e $md_wifi_lock`

case $BLOCK_BUTTON in
  1) $HOME/.config/i3/scripts/run-network ;;
  3) $HOME/.config/i3/scripts/dunst-vpn ;;
esac

device="${BLOCK_INSTANCE:-wlan0}"
status=$(cat /sys/class/net/${device}/operstate)

URGENT_VALUE=20

if [[ "${status}" == "up" ]]; then
  if [[ -d "/sys/class/net/${device}/wireless" ]]; then

    connected=$(nordvpn status | grep -wo Connected);

    if [[ "${connected}" = "Connected" ]]; then
      glyph=$glyph_vpn_wifi
    else
      glyph=$glyph_wifi
    fi

    quality=$(grep ${device} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
    set-label "$glyph ${quality}%" i3.block.fgrnd

    if [[ "${quality}" -le "${URGENT_VALUE}" ]]; then
      exit 33
    fi
  else
    set-label on i3.block.fgrnd
  fi
fi
