#!/usr/bin/bash

. $HOME/.config/i3/scripts/set-label

# icons from icons-in-terminal
. $HOME/.local/share/icons-in-terminal/icons_bash.sh
glyph_update=`echo -e $fa_arrow_circle_up`

urgent_value=5
package_count=$(/usr/bin/checkupdates | wc -l)
label="$glyph_update ${package_count}<span> </span>"

if [[ "${package_count}" -gt 0 ]]; then
  set-label "$label" i3.block.fgrnd
  if [[ "${package_count}" -gt "${urgent_value}" ]]; then
    exit 33
  fi
else
  echo "" # no updates
fi

# update on left click
case $BLOCK_BUTTON in
  1) $HOME/.config/i3/scripts/run-updates && echo "" ;;
esac
