#!/bin/bash

. $HOME/.config/i3/scripts/set-font
. $HOME/.config/i3/scripts/get-color

icon=$HOME/.config/dunst/icons/calendar.png
today=`date '+%e'`
fg=`get-color i3.bgrnd`
bg=`get-color cyn`
calendar=`set-font "$(cal -m)"`

# replace today with colored today
calendar=${calendar/" $today "/" </span><span font-family='monospace' background='$bg' color='$fg'>$today</span><span font-family='monospace'> "}

notify-send "Calendar" "$calendar" -i "$icon"
