#!/bin/bash

COLS="name,type,size,mountpoint"
ICON=$DOTS/dunst/icons/drive-harddisk-usb.png

drives="$(lsblk -rpo "$COLS" | awk '$2=="disk"&&$4==""&&!/sda/{printf "%s (%s)\n",$1,$3}')"
[ -z "$drives" ] && notify-send "USB" "Nothing to mount." -i $ICON && exit 1
chosen="$(echo "$drives" | rofi -dmenu -p "Mount which drive?" | awk '{print $1}')"
[ -z "$chosen" ] && exit 1
notify=$(udisksctl mount -b "$chosen")
notify-send "USB" "$notify" -i $ICON
